version: 2

jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
     environment:
        APP_NAME: w2f2
        BUILD_TARGET_DIR: .
    steps:
      - checkout
      - run: lein uberjar
  deploy:
    machine:
      services:
        - docker
    steps:
      - checkout
      - run: wget https://raw.githubusercontent.com/kolov/k8s-stuff/master/circleci/deploy-aws.sh
      - run: chmod +x deploy-aws.sh
      - run: ./deploy-aws.sh
    branches:
      only:
        - workflows

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy
