kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-w2f2
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi